version: "2.1"

services:

  api:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:9.6.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=place_me_test
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10
